wipe = true
pkgname = "models"
output = "internal/models/psql"
no-tests = true

[crdb]
dbname = "governor_test"
host = "localhost"
port = 26257
user = "root"
sslmode = "disable"
blacklist = ["goose_db_version", "notification_defaults"]

[psql]
dbname = "governor_test"
host = "pg"
port = 5432
user = "postgres"
pass = "postgres"
sslmode = "disable"
blacklist = ["goose_db_version", "notification_defaults"]
