// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	ApplicationTypes             string
	Applications                 string
	AuditEvents                  string
	ExtensionResourceDefinitions string
	Extensions                   string
	GroupApplicationRequests     string
	GroupApplications            string
	GroupHierarchies             string
	GroupMembershipRequests      string
	GroupMemberships             string
	GroupOrganizations           string
	Groups                       string
	NotificationPreferences      string
	NotificationTargets          string
	NotificationTypes            string
	Organizations                string
	SystemExtensionResources     string
	UserExtensionResources       string
	Users                        string
}{
	ApplicationTypes:             "application_types",
	Applications:                 "applications",
	AuditEvents:                  "audit_events",
	ExtensionResourceDefinitions: "extension_resource_definitions",
	Extensions:                   "extensions",
	GroupApplicationRequests:     "group_application_requests",
	GroupApplications:            "group_applications",
	GroupHierarchies:             "group_hierarchies",
	GroupMembershipRequests:      "group_membership_requests",
	GroupMemberships:             "group_memberships",
	GroupOrganizations:           "group_organizations",
	Groups:                       "groups",
	NotificationPreferences:      "notification_preferences",
	NotificationTargets:          "notification_targets",
	NotificationTypes:            "notification_types",
	Organizations:                "organizations",
	SystemExtensionResources:     "system_extension_resources",
	UserExtensionResources:       "user_extension_resources",
	Users:                        "users",
}
