// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// GroupApplication is an object representing the database table.
type GroupApplication struct {
	ID            string    `boil:"id" json:"id" toml:"id" yaml:"id"`
	GroupID       string    `boil:"group_id" json:"group_id" toml:"group_id" yaml:"group_id"`
	ApplicationID string    `boil:"application_id" json:"application_id" toml:"application_id" yaml:"application_id"`
	CreatedAt     time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt     time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt     null.Time `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`

	R *groupApplicationR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L groupApplicationL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var GroupApplicationColumns = struct {
	ID            string
	GroupID       string
	ApplicationID string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     string
}{
	ID:            "id",
	GroupID:       "group_id",
	ApplicationID: "application_id",
	CreatedAt:     "created_at",
	UpdatedAt:     "updated_at",
	DeletedAt:     "deleted_at",
}

var GroupApplicationTableColumns = struct {
	ID            string
	GroupID       string
	ApplicationID string
	CreatedAt     string
	UpdatedAt     string
	DeletedAt     string
}{
	ID:            "group_applications.id",
	GroupID:       "group_applications.group_id",
	ApplicationID: "group_applications.application_id",
	CreatedAt:     "group_applications.created_at",
	UpdatedAt:     "group_applications.updated_at",
	DeletedAt:     "group_applications.deleted_at",
}

// Generated where

var GroupApplicationWhere = struct {
	ID            whereHelperstring
	GroupID       whereHelperstring
	ApplicationID whereHelperstring
	CreatedAt     whereHelpertime_Time
	UpdatedAt     whereHelpertime_Time
	DeletedAt     whereHelpernull_Time
}{
	ID:            whereHelperstring{field: "\"group_applications\".\"id\""},
	GroupID:       whereHelperstring{field: "\"group_applications\".\"group_id\""},
	ApplicationID: whereHelperstring{field: "\"group_applications\".\"application_id\""},
	CreatedAt:     whereHelpertime_Time{field: "\"group_applications\".\"created_at\""},
	UpdatedAt:     whereHelpertime_Time{field: "\"group_applications\".\"updated_at\""},
	DeletedAt:     whereHelpernull_Time{field: "\"group_applications\".\"deleted_at\""},
}

// GroupApplicationRels is where relationship names are stored.
var GroupApplicationRels = struct {
	Application string
	Group       string
}{
	Application: "Application",
	Group:       "Group",
}

// groupApplicationR is where relationships are stored.
type groupApplicationR struct {
	Application *Application `boil:"Application" json:"Application" toml:"Application" yaml:"Application"`
	Group       *Group       `boil:"Group" json:"Group" toml:"Group" yaml:"Group"`
}

// NewStruct creates a new relationship struct
func (*groupApplicationR) NewStruct() *groupApplicationR {
	return &groupApplicationR{}
}

func (o *GroupApplication) GetApplication() *Application {
	if o == nil {
		return nil
	}

	return o.R.GetApplication()
}

func (r *groupApplicationR) GetApplication() *Application {
	if r == nil {
		return nil
	}

	return r.Application
}

func (o *GroupApplication) GetGroup() *Group {
	if o == nil {
		return nil
	}

	return o.R.GetGroup()
}

func (r *groupApplicationR) GetGroup() *Group {
	if r == nil {
		return nil
	}

	return r.Group
}

// groupApplicationL is where Load methods for each relationship are stored.
type groupApplicationL struct{}

var (
	groupApplicationAllColumns            = []string{"id", "group_id", "application_id", "created_at", "updated_at", "deleted_at"}
	groupApplicationColumnsWithoutDefault = []string{"group_id", "application_id"}
	groupApplicationColumnsWithDefault    = []string{"id", "created_at", "updated_at", "deleted_at"}
	groupApplicationPrimaryKeyColumns     = []string{"id"}
	groupApplicationGeneratedColumns      = []string{}
)

type (
	// GroupApplicationSlice is an alias for a slice of pointers to GroupApplication.
	// This should almost always be used instead of []GroupApplication.
	GroupApplicationSlice []*GroupApplication
	// GroupApplicationHook is the signature for custom GroupApplication hook methods
	GroupApplicationHook func(context.Context, boil.ContextExecutor, *GroupApplication) error

	groupApplicationQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	groupApplicationType                 = reflect.TypeOf(&GroupApplication{})
	groupApplicationMapping              = queries.MakeStructMapping(groupApplicationType)
	groupApplicationPrimaryKeyMapping, _ = queries.BindMapping(groupApplicationType, groupApplicationMapping, groupApplicationPrimaryKeyColumns)
	groupApplicationInsertCacheMut       sync.RWMutex
	groupApplicationInsertCache          = make(map[string]insertCache)
	groupApplicationUpdateCacheMut       sync.RWMutex
	groupApplicationUpdateCache          = make(map[string]updateCache)
	groupApplicationUpsertCacheMut       sync.RWMutex
	groupApplicationUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var groupApplicationAfterSelectMu sync.Mutex
var groupApplicationAfterSelectHooks []GroupApplicationHook

var groupApplicationBeforeInsertMu sync.Mutex
var groupApplicationBeforeInsertHooks []GroupApplicationHook
var groupApplicationAfterInsertMu sync.Mutex
var groupApplicationAfterInsertHooks []GroupApplicationHook

var groupApplicationBeforeUpdateMu sync.Mutex
var groupApplicationBeforeUpdateHooks []GroupApplicationHook
var groupApplicationAfterUpdateMu sync.Mutex
var groupApplicationAfterUpdateHooks []GroupApplicationHook

var groupApplicationBeforeDeleteMu sync.Mutex
var groupApplicationBeforeDeleteHooks []GroupApplicationHook
var groupApplicationAfterDeleteMu sync.Mutex
var groupApplicationAfterDeleteHooks []GroupApplicationHook

var groupApplicationBeforeUpsertMu sync.Mutex
var groupApplicationBeforeUpsertHooks []GroupApplicationHook
var groupApplicationAfterUpsertMu sync.Mutex
var groupApplicationAfterUpsertHooks []GroupApplicationHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *GroupApplication) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *GroupApplication) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *GroupApplication) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *GroupApplication) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *GroupApplication) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *GroupApplication) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *GroupApplication) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *GroupApplication) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *GroupApplication) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range groupApplicationAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddGroupApplicationHook registers your hook function for all future operations.
func AddGroupApplicationHook(hookPoint boil.HookPoint, groupApplicationHook GroupApplicationHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		groupApplicationAfterSelectMu.Lock()
		groupApplicationAfterSelectHooks = append(groupApplicationAfterSelectHooks, groupApplicationHook)
		groupApplicationAfterSelectMu.Unlock()
	case boil.BeforeInsertHook:
		groupApplicationBeforeInsertMu.Lock()
		groupApplicationBeforeInsertHooks = append(groupApplicationBeforeInsertHooks, groupApplicationHook)
		groupApplicationBeforeInsertMu.Unlock()
	case boil.AfterInsertHook:
		groupApplicationAfterInsertMu.Lock()
		groupApplicationAfterInsertHooks = append(groupApplicationAfterInsertHooks, groupApplicationHook)
		groupApplicationAfterInsertMu.Unlock()
	case boil.BeforeUpdateHook:
		groupApplicationBeforeUpdateMu.Lock()
		groupApplicationBeforeUpdateHooks = append(groupApplicationBeforeUpdateHooks, groupApplicationHook)
		groupApplicationBeforeUpdateMu.Unlock()
	case boil.AfterUpdateHook:
		groupApplicationAfterUpdateMu.Lock()
		groupApplicationAfterUpdateHooks = append(groupApplicationAfterUpdateHooks, groupApplicationHook)
		groupApplicationAfterUpdateMu.Unlock()
	case boil.BeforeDeleteHook:
		groupApplicationBeforeDeleteMu.Lock()
		groupApplicationBeforeDeleteHooks = append(groupApplicationBeforeDeleteHooks, groupApplicationHook)
		groupApplicationBeforeDeleteMu.Unlock()
	case boil.AfterDeleteHook:
		groupApplicationAfterDeleteMu.Lock()
		groupApplicationAfterDeleteHooks = append(groupApplicationAfterDeleteHooks, groupApplicationHook)
		groupApplicationAfterDeleteMu.Unlock()
	case boil.BeforeUpsertHook:
		groupApplicationBeforeUpsertMu.Lock()
		groupApplicationBeforeUpsertHooks = append(groupApplicationBeforeUpsertHooks, groupApplicationHook)
		groupApplicationBeforeUpsertMu.Unlock()
	case boil.AfterUpsertHook:
		groupApplicationAfterUpsertMu.Lock()
		groupApplicationAfterUpsertHooks = append(groupApplicationAfterUpsertHooks, groupApplicationHook)
		groupApplicationAfterUpsertMu.Unlock()
	}
}

// One returns a single groupApplication record from the query.
func (q groupApplicationQuery) One(ctx context.Context, exec boil.ContextExecutor) (*GroupApplication, error) {
	o := &GroupApplication{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for group_applications")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all GroupApplication records from the query.
func (q groupApplicationQuery) All(ctx context.Context, exec boil.ContextExecutor) (GroupApplicationSlice, error) {
	var o []*GroupApplication

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to GroupApplication slice")
	}

	if len(groupApplicationAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all GroupApplication records in the query.
func (q groupApplicationQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count group_applications rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q groupApplicationQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if group_applications exists")
	}

	return count > 0, nil
}

// Application pointed to by the foreign key.
func (o *GroupApplication) Application(mods ...qm.QueryMod) applicationQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ApplicationID),
	}

	queryMods = append(queryMods, mods...)

	return Applications(queryMods...)
}

// Group pointed to by the foreign key.
func (o *GroupApplication) Group(mods ...qm.QueryMod) groupQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.GroupID),
	}

	queryMods = append(queryMods, mods...)

	return Groups(queryMods...)
}

// LoadApplication allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (groupApplicationL) LoadApplication(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGroupApplication interface{}, mods queries.Applicator) error {
	var slice []*GroupApplication
	var object *GroupApplication

	if singular {
		var ok bool
		object, ok = maybeGroupApplication.(*GroupApplication)
		if !ok {
			object = new(GroupApplication)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGroupApplication)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGroupApplication))
			}
		}
	} else {
		s, ok := maybeGroupApplication.(*[]*GroupApplication)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGroupApplication)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGroupApplication))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &groupApplicationR{}
		}
		args[object.ApplicationID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &groupApplicationR{}
			}

			args[obj.ApplicationID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`applications`),
		qm.WhereIn(`applications.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`applications.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Application")
	}

	var resultSlice []*Application
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Application")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for applications")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for applications")
	}

	if len(applicationAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Application = foreign
		if foreign.R == nil {
			foreign.R = &applicationR{}
		}
		foreign.R.GroupApplications = append(foreign.R.GroupApplications, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ApplicationID == foreign.ID {
				local.R.Application = foreign
				if foreign.R == nil {
					foreign.R = &applicationR{}
				}
				foreign.R.GroupApplications = append(foreign.R.GroupApplications, local)
				break
			}
		}
	}

	return nil
}

// LoadGroup allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (groupApplicationL) LoadGroup(ctx context.Context, e boil.ContextExecutor, singular bool, maybeGroupApplication interface{}, mods queries.Applicator) error {
	var slice []*GroupApplication
	var object *GroupApplication

	if singular {
		var ok bool
		object, ok = maybeGroupApplication.(*GroupApplication)
		if !ok {
			object = new(GroupApplication)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeGroupApplication)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeGroupApplication))
			}
		}
	} else {
		s, ok := maybeGroupApplication.(*[]*GroupApplication)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeGroupApplication)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeGroupApplication))
			}
		}
	}

	args := make(map[interface{}]struct{})
	if singular {
		if object.R == nil {
			object.R = &groupApplicationR{}
		}
		args[object.GroupID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &groupApplicationR{}
			}

			args[obj.GroupID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]interface{}, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`groups`),
		qm.WhereIn(`groups.id in ?`, argsSlice...),
		qmhelper.WhereIsNull(`groups.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Group")
	}

	var resultSlice []*Group
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Group")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for groups")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for groups")
	}

	if len(groupAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Group = foreign
		if foreign.R == nil {
			foreign.R = &groupR{}
		}
		foreign.R.GroupApplications = append(foreign.R.GroupApplications, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.GroupID == foreign.ID {
				local.R.Group = foreign
				if foreign.R == nil {
					foreign.R = &groupR{}
				}
				foreign.R.GroupApplications = append(foreign.R.GroupApplications, local)
				break
			}
		}
	}

	return nil
}

// SetApplication of the groupApplication to the related item.
// Sets o.R.Application to related.
// Adds o to related.R.GroupApplications.
func (o *GroupApplication) SetApplication(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Application) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"group_applications\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"application_id"}),
		strmangle.WhereClause("\"", "\"", 2, groupApplicationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ApplicationID = related.ID
	if o.R == nil {
		o.R = &groupApplicationR{
			Application: related,
		}
	} else {
		o.R.Application = related
	}

	if related.R == nil {
		related.R = &applicationR{
			GroupApplications: GroupApplicationSlice{o},
		}
	} else {
		related.R.GroupApplications = append(related.R.GroupApplications, o)
	}

	return nil
}

// SetGroup of the groupApplication to the related item.
// Sets o.R.Group to related.
// Adds o to related.R.GroupApplications.
func (o *GroupApplication) SetGroup(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Group) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"group_applications\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"group_id"}),
		strmangle.WhereClause("\"", "\"", 2, groupApplicationPrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.GroupID = related.ID
	if o.R == nil {
		o.R = &groupApplicationR{
			Group: related,
		}
	} else {
		o.R.Group = related
	}

	if related.R == nil {
		related.R = &groupR{
			GroupApplications: GroupApplicationSlice{o},
		}
	} else {
		related.R.GroupApplications = append(related.R.GroupApplications, o)
	}

	return nil
}

// GroupApplications retrieves all the records using an executor.
func GroupApplications(mods ...qm.QueryMod) groupApplicationQuery {
	mods = append(mods, qm.From("\"group_applications\""), qmhelper.WhereIsNull("\"group_applications\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"group_applications\".*"})
	}

	return groupApplicationQuery{q}
}

// FindGroupApplication retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindGroupApplication(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*GroupApplication, error) {
	groupApplicationObj := &GroupApplication{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"group_applications\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, groupApplicationObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from group_applications")
	}

	if err = groupApplicationObj.doAfterSelectHooks(ctx, exec); err != nil {
		return groupApplicationObj, err
	}

	return groupApplicationObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *GroupApplication) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no group_applications provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(groupApplicationColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	groupApplicationInsertCacheMut.RLock()
	cache, cached := groupApplicationInsertCache[key]
	groupApplicationInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			groupApplicationAllColumns,
			groupApplicationColumnsWithDefault,
			groupApplicationColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(groupApplicationType, groupApplicationMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(groupApplicationType, groupApplicationMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"group_applications\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"group_applications\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into group_applications")
	}

	if !cached {
		groupApplicationInsertCacheMut.Lock()
		groupApplicationInsertCache[key] = cache
		groupApplicationInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the GroupApplication.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *GroupApplication) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	groupApplicationUpdateCacheMut.RLock()
	cache, cached := groupApplicationUpdateCache[key]
	groupApplicationUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			groupApplicationAllColumns,
			groupApplicationPrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update group_applications, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"group_applications\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, groupApplicationPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(groupApplicationType, groupApplicationMapping, append(wl, groupApplicationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update group_applications row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for group_applications")
	}

	if !cached {
		groupApplicationUpdateCacheMut.Lock()
		groupApplicationUpdateCache[key] = cache
		groupApplicationUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q groupApplicationQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for group_applications")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for group_applications")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o GroupApplicationSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupApplicationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"group_applications\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, groupApplicationPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in groupApplication slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all groupApplication")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *GroupApplication) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no group_applications provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(groupApplicationColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	groupApplicationUpsertCacheMut.RLock()
	cache, cached := groupApplicationUpsertCache[key]
	groupApplicationUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			groupApplicationAllColumns,
			groupApplicationColumnsWithDefault,
			groupApplicationColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			groupApplicationAllColumns,
			groupApplicationPrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert group_applications, could not build update column list")
		}

		ret := strmangle.SetComplement(groupApplicationAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(groupApplicationPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert group_applications, could not build conflict column list")
			}

			conflict = make([]string, len(groupApplicationPrimaryKeyColumns))
			copy(conflict, groupApplicationPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"group_applications\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(groupApplicationType, groupApplicationMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(groupApplicationType, groupApplicationMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert group_applications")
	}

	if !cached {
		groupApplicationUpsertCacheMut.Lock()
		groupApplicationUpsertCache[key] = cache
		groupApplicationUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}

// Delete deletes a single GroupApplication record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *GroupApplication) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no GroupApplication provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), groupApplicationPrimaryKeyMapping)
		sql = "DELETE FROM \"group_applications\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"group_applications\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(groupApplicationType, groupApplicationMapping, append(wl, groupApplicationPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from group_applications")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for group_applications")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q groupApplicationQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no groupApplicationQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from group_applications")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for group_applications")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o GroupApplicationSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(groupApplicationBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupApplicationPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"group_applications\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, groupApplicationPrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupApplicationPrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"group_applications\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, groupApplicationPrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from groupApplication slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for group_applications")
	}

	if len(groupApplicationAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *GroupApplication) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindGroupApplication(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *GroupApplicationSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := GroupApplicationSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), groupApplicationPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"group_applications\".* FROM \"group_applications\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, groupApplicationPrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in GroupApplicationSlice")
	}

	*o = slice

	return nil
}

// GroupApplicationExists checks if the GroupApplication row exists.
func GroupApplicationExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"group_applications\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if group_applications exists")
	}

	return exists, nil
}

// Exists checks if the GroupApplication row exists.
func (o *GroupApplication) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return GroupApplicationExists(ctx, exec, o.ID)
}
