// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/friendsofgo/errors"
	"github.com/volatiletech/null/v8"
	"github.com/volatiletech/sqlboiler/v4/boil"
	"github.com/volatiletech/sqlboiler/v4/queries"
	"github.com/volatiletech/sqlboiler/v4/queries/qm"
	"github.com/volatiletech/sqlboiler/v4/queries/qmhelper"
	"github.com/volatiletech/sqlboiler/v4/types"
	"github.com/volatiletech/strmangle"
)

// UserExtensionResource is an object representing the database table.
type UserExtensionResource struct {
	ID                            string     `boil:"id" json:"id" toml:"id" yaml:"id"`
	Resource                      types.JSON `boil:"resource" json:"resource" toml:"resource" yaml:"resource"`
	CreatedAt                     time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt                     time.Time  `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`
	DeletedAt                     null.Time  `boil:"deleted_at" json:"deleted_at,omitempty" toml:"deleted_at" yaml:"deleted_at,omitempty"`
	UserID                        string     `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	ExtensionResourceDefinitionID string     `boil:"extension_resource_definition_id" json:"extension_resource_definition_id" toml:"extension_resource_definition_id" yaml:"extension_resource_definition_id"`

	R *userExtensionResourceR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L userExtensionResourceL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var UserExtensionResourceColumns = struct {
	ID                            string
	Resource                      string
	CreatedAt                     string
	UpdatedAt                     string
	DeletedAt                     string
	UserID                        string
	ExtensionResourceDefinitionID string
}{
	ID:                            "id",
	Resource:                      "resource",
	CreatedAt:                     "created_at",
	UpdatedAt:                     "updated_at",
	DeletedAt:                     "deleted_at",
	UserID:                        "user_id",
	ExtensionResourceDefinitionID: "extension_resource_definition_id",
}

var UserExtensionResourceTableColumns = struct {
	ID                            string
	Resource                      string
	CreatedAt                     string
	UpdatedAt                     string
	DeletedAt                     string
	UserID                        string
	ExtensionResourceDefinitionID string
}{
	ID:                            "user_extension_resources.id",
	Resource:                      "user_extension_resources.resource",
	CreatedAt:                     "user_extension_resources.created_at",
	UpdatedAt:                     "user_extension_resources.updated_at",
	DeletedAt:                     "user_extension_resources.deleted_at",
	UserID:                        "user_extension_resources.user_id",
	ExtensionResourceDefinitionID: "user_extension_resources.extension_resource_definition_id",
}

// Generated where

var UserExtensionResourceWhere = struct {
	ID                            whereHelperstring
	Resource                      whereHelpertypes_JSON
	CreatedAt                     whereHelpertime_Time
	UpdatedAt                     whereHelpertime_Time
	DeletedAt                     whereHelpernull_Time
	UserID                        whereHelperstring
	ExtensionResourceDefinitionID whereHelperstring
}{
	ID:                            whereHelperstring{field: "\"user_extension_resources\".\"id\""},
	Resource:                      whereHelpertypes_JSON{field: "\"user_extension_resources\".\"resource\""},
	CreatedAt:                     whereHelpertime_Time{field: "\"user_extension_resources\".\"created_at\""},
	UpdatedAt:                     whereHelpertime_Time{field: "\"user_extension_resources\".\"updated_at\""},
	DeletedAt:                     whereHelpernull_Time{field: "\"user_extension_resources\".\"deleted_at\""},
	UserID:                        whereHelperstring{field: "\"user_extension_resources\".\"user_id\""},
	ExtensionResourceDefinitionID: whereHelperstring{field: "\"user_extension_resources\".\"extension_resource_definition_id\""},
}

// UserExtensionResourceRels is where relationship names are stored.
var UserExtensionResourceRels = struct {
	User                        string
	ExtensionResourceDefinition string
}{
	User:                        "User",
	ExtensionResourceDefinition: "ExtensionResourceDefinition",
}

// userExtensionResourceR is where relationships are stored.
type userExtensionResourceR struct {
	User                        *User                        `boil:"User" json:"User" toml:"User" yaml:"User"`
	ExtensionResourceDefinition *ExtensionResourceDefinition `boil:"ExtensionResourceDefinition" json:"ExtensionResourceDefinition" toml:"ExtensionResourceDefinition" yaml:"ExtensionResourceDefinition"`
}

// NewStruct creates a new relationship struct
func (*userExtensionResourceR) NewStruct() *userExtensionResourceR {
	return &userExtensionResourceR{}
}

func (r *userExtensionResourceR) GetUser() *User {
	if r == nil {
		return nil
	}
	return r.User
}

func (r *userExtensionResourceR) GetExtensionResourceDefinition() *ExtensionResourceDefinition {
	if r == nil {
		return nil
	}
	return r.ExtensionResourceDefinition
}

// userExtensionResourceL is where Load methods for each relationship are stored.
type userExtensionResourceL struct{}

var (
	userExtensionResourceAllColumns            = []string{"id", "resource", "created_at", "updated_at", "deleted_at", "user_id", "extension_resource_definition_id"}
	userExtensionResourceColumnsWithoutDefault = []string{"resource", "user_id", "extension_resource_definition_id"}
	userExtensionResourceColumnsWithDefault    = []string{"id", "created_at", "updated_at", "deleted_at"}
	userExtensionResourcePrimaryKeyColumns     = []string{"id"}
	userExtensionResourceGeneratedColumns      = []string{}
)

type (
	// UserExtensionResourceSlice is an alias for a slice of pointers to UserExtensionResource.
	// This should almost always be used instead of []UserExtensionResource.
	UserExtensionResourceSlice []*UserExtensionResource
	// UserExtensionResourceHook is the signature for custom UserExtensionResource hook methods
	UserExtensionResourceHook func(context.Context, boil.ContextExecutor, *UserExtensionResource) error

	userExtensionResourceQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	userExtensionResourceType                 = reflect.TypeOf(&UserExtensionResource{})
	userExtensionResourceMapping              = queries.MakeStructMapping(userExtensionResourceType)
	userExtensionResourcePrimaryKeyMapping, _ = queries.BindMapping(userExtensionResourceType, userExtensionResourceMapping, userExtensionResourcePrimaryKeyColumns)
	userExtensionResourceInsertCacheMut       sync.RWMutex
	userExtensionResourceInsertCache          = make(map[string]insertCache)
	userExtensionResourceUpdateCacheMut       sync.RWMutex
	userExtensionResourceUpdateCache          = make(map[string]updateCache)
	userExtensionResourceUpsertCacheMut       sync.RWMutex
	userExtensionResourceUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

var userExtensionResourceAfterSelectHooks []UserExtensionResourceHook

var userExtensionResourceBeforeInsertHooks []UserExtensionResourceHook
var userExtensionResourceAfterInsertHooks []UserExtensionResourceHook

var userExtensionResourceBeforeUpdateHooks []UserExtensionResourceHook
var userExtensionResourceAfterUpdateHooks []UserExtensionResourceHook

var userExtensionResourceBeforeDeleteHooks []UserExtensionResourceHook
var userExtensionResourceAfterDeleteHooks []UserExtensionResourceHook

var userExtensionResourceBeforeUpsertHooks []UserExtensionResourceHook
var userExtensionResourceAfterUpsertHooks []UserExtensionResourceHook

// doAfterSelectHooks executes all "after Select" hooks.
func (o *UserExtensionResource) doAfterSelectHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceAfterSelectHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeInsertHooks executes all "before insert" hooks.
func (o *UserExtensionResource) doBeforeInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceBeforeInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterInsertHooks executes all "after Insert" hooks.
func (o *UserExtensionResource) doAfterInsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceAfterInsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpdateHooks executes all "before Update" hooks.
func (o *UserExtensionResource) doBeforeUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceBeforeUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpdateHooks executes all "after Update" hooks.
func (o *UserExtensionResource) doAfterUpdateHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceAfterUpdateHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeDeleteHooks executes all "before Delete" hooks.
func (o *UserExtensionResource) doBeforeDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceBeforeDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterDeleteHooks executes all "after Delete" hooks.
func (o *UserExtensionResource) doAfterDeleteHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceAfterDeleteHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doBeforeUpsertHooks executes all "before Upsert" hooks.
func (o *UserExtensionResource) doBeforeUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceBeforeUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// doAfterUpsertHooks executes all "after Upsert" hooks.
func (o *UserExtensionResource) doAfterUpsertHooks(ctx context.Context, exec boil.ContextExecutor) (err error) {
	if boil.HooksAreSkipped(ctx) {
		return nil
	}

	for _, hook := range userExtensionResourceAfterUpsertHooks {
		if err := hook(ctx, exec, o); err != nil {
			return err
		}
	}

	return nil
}

// AddUserExtensionResourceHook registers your hook function for all future operations.
func AddUserExtensionResourceHook(hookPoint boil.HookPoint, userExtensionResourceHook UserExtensionResourceHook) {
	switch hookPoint {
	case boil.AfterSelectHook:
		userExtensionResourceAfterSelectHooks = append(userExtensionResourceAfterSelectHooks, userExtensionResourceHook)
	case boil.BeforeInsertHook:
		userExtensionResourceBeforeInsertHooks = append(userExtensionResourceBeforeInsertHooks, userExtensionResourceHook)
	case boil.AfterInsertHook:
		userExtensionResourceAfterInsertHooks = append(userExtensionResourceAfterInsertHooks, userExtensionResourceHook)
	case boil.BeforeUpdateHook:
		userExtensionResourceBeforeUpdateHooks = append(userExtensionResourceBeforeUpdateHooks, userExtensionResourceHook)
	case boil.AfterUpdateHook:
		userExtensionResourceAfterUpdateHooks = append(userExtensionResourceAfterUpdateHooks, userExtensionResourceHook)
	case boil.BeforeDeleteHook:
		userExtensionResourceBeforeDeleteHooks = append(userExtensionResourceBeforeDeleteHooks, userExtensionResourceHook)
	case boil.AfterDeleteHook:
		userExtensionResourceAfterDeleteHooks = append(userExtensionResourceAfterDeleteHooks, userExtensionResourceHook)
	case boil.BeforeUpsertHook:
		userExtensionResourceBeforeUpsertHooks = append(userExtensionResourceBeforeUpsertHooks, userExtensionResourceHook)
	case boil.AfterUpsertHook:
		userExtensionResourceAfterUpsertHooks = append(userExtensionResourceAfterUpsertHooks, userExtensionResourceHook)
	}
}

// One returns a single userExtensionResource record from the query.
func (q userExtensionResourceQuery) One(ctx context.Context, exec boil.ContextExecutor) (*UserExtensionResource, error) {
	o := &UserExtensionResource{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for user_extension_resources")
	}

	if err := o.doAfterSelectHooks(ctx, exec); err != nil {
		return o, err
	}

	return o, nil
}

// All returns all UserExtensionResource records from the query.
func (q userExtensionResourceQuery) All(ctx context.Context, exec boil.ContextExecutor) (UserExtensionResourceSlice, error) {
	var o []*UserExtensionResource

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to UserExtensionResource slice")
	}

	if len(userExtensionResourceAfterSelectHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterSelectHooks(ctx, exec); err != nil {
				return o, err
			}
		}
	}

	return o, nil
}

// Count returns the count of all UserExtensionResource records in the query.
func (q userExtensionResourceQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count user_extension_resources rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q userExtensionResourceQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if user_extension_resources exists")
	}

	return count > 0, nil
}

// User pointed to by the foreign key.
func (o *UserExtensionResource) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// ExtensionResourceDefinition pointed to by the foreign key.
func (o *UserExtensionResource) ExtensionResourceDefinition(mods ...qm.QueryMod) extensionResourceDefinitionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ExtensionResourceDefinitionID),
	}

	queryMods = append(queryMods, mods...)

	return ExtensionResourceDefinitions(queryMods...)
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userExtensionResourceL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserExtensionResource interface{}, mods queries.Applicator) error {
	var slice []*UserExtensionResource
	var object *UserExtensionResource

	if singular {
		var ok bool
		object, ok = maybeUserExtensionResource.(*UserExtensionResource)
		if !ok {
			object = new(UserExtensionResource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserExtensionResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserExtensionResource))
			}
		}
	} else {
		s, ok := maybeUserExtensionResource.(*[]*UserExtensionResource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserExtensionResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserExtensionResource))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userExtensionResourceR{}
		}
		args = append(args, object.UserID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userExtensionResourceR{}
			}

			for _, a := range args {
				if a == obj.UserID {
					continue Outer
				}
			}

			args = append(args, obj.UserID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, args...),
		qmhelper.WhereIsNull(`users.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(userAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UserExtensionResources = append(foreign.R.UserExtensionResources, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UserExtensionResources = append(foreign.R.UserExtensionResources, local)
				break
			}
		}
	}

	return nil
}

// LoadExtensionResourceDefinition allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (userExtensionResourceL) LoadExtensionResourceDefinition(ctx context.Context, e boil.ContextExecutor, singular bool, maybeUserExtensionResource interface{}, mods queries.Applicator) error {
	var slice []*UserExtensionResource
	var object *UserExtensionResource

	if singular {
		var ok bool
		object, ok = maybeUserExtensionResource.(*UserExtensionResource)
		if !ok {
			object = new(UserExtensionResource)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeUserExtensionResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeUserExtensionResource))
			}
		}
	} else {
		s, ok := maybeUserExtensionResource.(*[]*UserExtensionResource)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeUserExtensionResource)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeUserExtensionResource))
			}
		}
	}

	args := make([]interface{}, 0, 1)
	if singular {
		if object.R == nil {
			object.R = &userExtensionResourceR{}
		}
		args = append(args, object.ExtensionResourceDefinitionID)

	} else {
	Outer:
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &userExtensionResourceR{}
			}

			for _, a := range args {
				if a == obj.ExtensionResourceDefinitionID {
					continue Outer
				}
			}

			args = append(args, obj.ExtensionResourceDefinitionID)

		}
	}

	if len(args) == 0 {
		return nil
	}

	query := NewQuery(
		qm.From(`extension_resource_definitions`),
		qm.WhereIn(`extension_resource_definitions.id in ?`, args...),
		qmhelper.WhereIsNull(`extension_resource_definitions.deleted_at`),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load ExtensionResourceDefinition")
	}

	var resultSlice []*ExtensionResourceDefinition
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice ExtensionResourceDefinition")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for extension_resource_definitions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for extension_resource_definitions")
	}

	if len(extensionResourceDefinitionAfterSelectHooks) != 0 {
		for _, obj := range resultSlice {
			if err := obj.doAfterSelectHooks(ctx, e); err != nil {
				return err
			}
		}
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ExtensionResourceDefinition = foreign
		if foreign.R == nil {
			foreign.R = &extensionResourceDefinitionR{}
		}
		foreign.R.UserExtensionResources = append(foreign.R.UserExtensionResources, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.ExtensionResourceDefinitionID == foreign.ID {
				local.R.ExtensionResourceDefinition = foreign
				if foreign.R == nil {
					foreign.R = &extensionResourceDefinitionR{}
				}
				foreign.R.UserExtensionResources = append(foreign.R.UserExtensionResources, local)
				break
			}
		}
	}

	return nil
}

// SetUser of the userExtensionResource to the related item.
// Sets o.R.User to related.
// Adds o to related.R.UserExtensionResources.
func (o *UserExtensionResource) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_extension_resources\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, userExtensionResourcePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &userExtensionResourceR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			UserExtensionResources: UserExtensionResourceSlice{o},
		}
	} else {
		related.R.UserExtensionResources = append(related.R.UserExtensionResources, o)
	}

	return nil
}

// SetExtensionResourceDefinition of the userExtensionResource to the related item.
// Sets o.R.ExtensionResourceDefinition to related.
// Adds o to related.R.UserExtensionResources.
func (o *UserExtensionResource) SetExtensionResourceDefinition(ctx context.Context, exec boil.ContextExecutor, insert bool, related *ExtensionResourceDefinition) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"user_extension_resources\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"extension_resource_definition_id"}),
		strmangle.WhereClause("\"", "\"", 2, userExtensionResourcePrimaryKeyColumns),
	)
	values := []interface{}{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.ExtensionResourceDefinitionID = related.ID
	if o.R == nil {
		o.R = &userExtensionResourceR{
			ExtensionResourceDefinition: related,
		}
	} else {
		o.R.ExtensionResourceDefinition = related
	}

	if related.R == nil {
		related.R = &extensionResourceDefinitionR{
			UserExtensionResources: UserExtensionResourceSlice{o},
		}
	} else {
		related.R.UserExtensionResources = append(related.R.UserExtensionResources, o)
	}

	return nil
}

// UserExtensionResources retrieves all the records using an executor.
func UserExtensionResources(mods ...qm.QueryMod) userExtensionResourceQuery {
	mods = append(mods, qm.From("\"user_extension_resources\""), qmhelper.WhereIsNull("\"user_extension_resources\".\"deleted_at\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"user_extension_resources\".*"})
	}

	return userExtensionResourceQuery{q}
}

// FindUserExtensionResource retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindUserExtensionResource(ctx context.Context, exec boil.ContextExecutor, iD string, selectCols ...string) (*UserExtensionResource, error) {
	userExtensionResourceObj := &UserExtensionResource{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"user_extension_resources\" where \"id\"=$1 and \"deleted_at\" is null", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, userExtensionResourceObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from user_extension_resources")
	}

	if err = userExtensionResourceObj.doAfterSelectHooks(ctx, exec); err != nil {
		return userExtensionResourceObj, err
	}

	return userExtensionResourceObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *UserExtensionResource) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_extension_resources provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	if err := o.doBeforeInsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userExtensionResourceColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	userExtensionResourceInsertCacheMut.RLock()
	cache, cached := userExtensionResourceInsertCache[key]
	userExtensionResourceInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			userExtensionResourceAllColumns,
			userExtensionResourceColumnsWithDefault,
			userExtensionResourceColumnsWithoutDefault,
			nzDefaults,
		)

		cache.valueMapping, err = queries.BindMapping(userExtensionResourceType, userExtensionResourceMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(userExtensionResourceType, userExtensionResourceMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"user_extension_resources\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"user_extension_resources\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into user_extension_resources")
	}

	if !cached {
		userExtensionResourceInsertCacheMut.Lock()
		userExtensionResourceInsertCache[key] = cache
		userExtensionResourceInsertCacheMut.Unlock()
	}

	return o.doAfterInsertHooks(ctx, exec)
}

// Update uses an executor to update the UserExtensionResource.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *UserExtensionResource) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	if err = o.doBeforeUpdateHooks(ctx, exec); err != nil {
		return 0, err
	}
	key := makeCacheKey(columns, nil)
	userExtensionResourceUpdateCacheMut.RLock()
	cache, cached := userExtensionResourceUpdateCache[key]
	userExtensionResourceUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			userExtensionResourceAllColumns,
			userExtensionResourcePrimaryKeyColumns,
		)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update user_extension_resources, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"user_extension_resources\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, userExtensionResourcePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(userExtensionResourceType, userExtensionResourceMapping, append(wl, userExtensionResourcePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update user_extension_resources row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for user_extension_resources")
	}

	if !cached {
		userExtensionResourceUpdateCacheMut.Lock()
		userExtensionResourceUpdateCache[key] = cache
		userExtensionResourceUpdateCacheMut.Unlock()
	}

	return rowsAff, o.doAfterUpdateHooks(ctx, exec)
}

// UpdateAll updates all rows with the specified column values.
func (q userExtensionResourceQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for user_extension_resources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for user_extension_resources")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o UserExtensionResourceSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]interface{}, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userExtensionResourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"user_extension_resources\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, userExtensionResourcePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in userExtensionResource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all userExtensionResource")
	}
	return rowsAff, nil
}

// Delete deletes a single UserExtensionResource record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *UserExtensionResource) Delete(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no UserExtensionResource provided for delete")
	}

	if err := o.doBeforeDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), userExtensionResourcePrimaryKeyMapping)
		sql = "DELETE FROM \"user_extension_resources\" WHERE \"id\"=$1"
	} else {
		currTime := time.Now().In(boil.GetLocation())
		o.DeletedAt = null.TimeFrom(currTime)
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"user_extension_resources\" SET %s WHERE \"id\"=$2",
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		valueMapping, err := queries.BindMapping(userExtensionResourceType, userExtensionResourceMapping, append(wl, userExtensionResourcePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
		args = queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), valueMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from user_extension_resources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for user_extension_resources")
	}

	if err := o.doAfterDeleteHooks(ctx, exec); err != nil {
		return 0, err
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q userExtensionResourceQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no userExtensionResourceQuery provided for delete all")
	}

	if hardDelete {
		queries.SetDelete(q.Query)
	} else {
		currTime := time.Now().In(boil.GetLocation())
		queries.SetUpdate(q.Query, M{"deleted_at": currTime})
	}

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from user_extension_resources")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_extension_resources")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o UserExtensionResourceSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor, hardDelete bool) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	if len(userExtensionResourceBeforeDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doBeforeDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	var (
		sql  string
		args []interface{}
	)
	if hardDelete {
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userExtensionResourcePrimaryKeyMapping)
			args = append(args, pkeyArgs...)
		}
		sql = "DELETE FROM \"user_extension_resources\" WHERE " +
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userExtensionResourcePrimaryKeyColumns, len(o))
	} else {
		currTime := time.Now().In(boil.GetLocation())
		for _, obj := range o {
			pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userExtensionResourcePrimaryKeyMapping)
			args = append(args, pkeyArgs...)
			obj.DeletedAt = null.TimeFrom(currTime)
		}
		wl := []string{"deleted_at"}
		sql = fmt.Sprintf("UPDATE \"user_extension_resources\" SET %s WHERE "+
			strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 2, userExtensionResourcePrimaryKeyColumns, len(o)),
			strmangle.SetParamNames("\"", "\"", 1, wl),
		)
		args = append([]interface{}{currTime}, args...)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from userExtensionResource slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for user_extension_resources")
	}

	if len(userExtensionResourceAfterDeleteHooks) != 0 {
		for _, obj := range o {
			if err := obj.doAfterDeleteHooks(ctx, exec); err != nil {
				return 0, err
			}
		}
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *UserExtensionResource) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindUserExtensionResource(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *UserExtensionResourceSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := UserExtensionResourceSlice{}
	var args []interface{}
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), userExtensionResourcePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"user_extension_resources\".* FROM \"user_extension_resources\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, userExtensionResourcePrimaryKeyColumns, len(*o)) +
		"and \"deleted_at\" is null"

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in UserExtensionResourceSlice")
	}

	*o = slice

	return nil
}

// UserExtensionResourceExists checks if the UserExtensionResource row exists.
func UserExtensionResourceExists(ctx context.Context, exec boil.ContextExecutor, iD string) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"user_extension_resources\" where \"id\"=$1 and \"deleted_at\" is null limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if user_extension_resources exists")
	}

	return exists, nil
}

// Exists checks if the UserExtensionResource row exists.
func (o *UserExtensionResource) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return UserExtensionResourceExists(ctx, exec, o.ID)
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *UserExtensionResource) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns) error {
	if o == nil {
		return errors.New("models: no user_extension_resources provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	if err := o.doBeforeUpsertHooks(ctx, exec); err != nil {
		return err
	}

	nzDefaults := queries.NonZeroDefaultSet(userExtensionResourceColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	userExtensionResourceUpsertCacheMut.RLock()
	cache, cached := userExtensionResourceUpsertCache[key]
	userExtensionResourceUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, ret := insertColumns.InsertColumnSet(
			userExtensionResourceAllColumns,
			userExtensionResourceColumnsWithDefault,
			userExtensionResourceColumnsWithoutDefault,
			nzDefaults,
		)
		update := updateColumns.UpdateColumnSet(
			userExtensionResourceAllColumns,
			userExtensionResourcePrimaryKeyColumns,
		)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert user_extension_resources, could not build update column list")
		}

		conflict := conflictColumns
		if len(conflict) == 0 {
			conflict = make([]string, len(userExtensionResourcePrimaryKeyColumns))
			copy(conflict, userExtensionResourcePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryCockroachDB(dialect, "\"user_extension_resources\"", updateOnConflict, ret, update, conflict, insert)

		cache.valueMapping, err = queries.BindMapping(userExtensionResourceType, userExtensionResourceMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(userExtensionResourceType, userExtensionResourceMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []interface{}
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.DebugMode {
		_, _ = fmt.Fprintln(boil.DebugWriter, cache.query)
		_, _ = fmt.Fprintln(boil.DebugWriter, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if err == sql.ErrNoRows {
			err = nil // CockcorachDB doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert user_extension_resources")
	}

	if !cached {
		userExtensionResourceUpsertCacheMut.Lock()
		userExtensionResourceUpsertCache[key] = cache
		userExtensionResourceUpsertCacheMut.Unlock()
	}

	return o.doAfterUpsertHooks(ctx, exec)
}
