{{- if .Values.db.secrets.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: db-uri
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  GOVERNOR_DB_URI: {{ .Values.db.secrets.uri }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "common.names.fullname" . }}-crdb-ca
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.db.secrets.crdbCrt }}
{{- end }}
{{- if .Values.nats.secrets.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "common.names.fullname" . }}-nats-creds
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  governor-nats-client-creds:: {{ .Values.nats.secrets.clientCreds }}
{{- end }}
{{- if .Values.tracing.secrets.enabled }}
---
kind: Secret
apiVersion: v1
metadata:
  name: {{ template "common.names.fullname" . }}-nats-creds
  labels: {{- include "common.labels.standard" . | nindent 4 }}
type: Opaque
data:
  honeycomb-key:: {{ .Values.tracing.secrets.honeycombKey }}
{{- end }}
