---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "common.names.fullname" . }}-api
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 3001
  selector: {{ include "common.labels.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
  sessionAffinity: None
  type: ClusterIP
