name: openapi-schema

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  openapi-bundle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install dependencies
        run: |
          npm install -g @redocly/cli
      - name: Bundle OpenAPI Spec
        run: |
          redocly bundle openapi/v1alpha1/openapi.yaml -o _site/openapi-bundle.yaml
          redocly build-docs openapi/v1alpha1/openapi.yaml --title "Governor API" -o _site/index.html
      - name: Upload OpenAPI Bundle
        uses: actions/upload-pages-artifact@v3
        with:
          retention-days: 1

  publish-pages:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    needs: openapi-bundle
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
